# Generated by Django 4.1 on 2022-08-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("SHIRT", "Shrit"),
                    ("SPORT_WARE", "Sport ware"),
                    ("OUTWARE", "Outware"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("PRIMARY", "primary"),
                    ("SECONDARY", "secondary"),
                    ("Danger", "danger"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
