# Generated by Django 4.1 on 2022-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="quantity", field=models.IntegerField(default=1),
        ),
    ]
